openai_api_key: input you openai API key here!
index_urls:
 - "https://qiita.com/MoriKen/items/da8d290dcefad81b478d"
 - "https://qiita.com/MoriKen/items/0b75ab291ab0d95c37c2"
 - "https://qiita.com/MoriKen/items/8387b279e968368783f1"
 - "https://qiita.com/MoriKen/items/d5cd6208143d6c40caff"
 - "https://qiita.com/MoriKen/items/87be494f048ea03fdab8"
 - "https://qiita.com/MoriKen/items/26483e86fb556f0dc5ce"
 - "https://qiita.com/MoriKen/items/239f69df2921cc64bd62"
 - "https://qiita.com/MoriKen/items/dfb6eb168649873589f0"
 - "https://qiita.com/MoriKen/items/74cbff9198f82f2b7ea8"
 - "https://qiita.com/MoriKen/items/65ac41abca9fdf6051be"
 - "https://qiita.com/MoriKen/items/0f2550a2adbdcd3da04e"
